events {}

http {
    upstream user-service {
        server user-service:8081;
    }

    upstream group-service {
        server group-service:8082;
    }

    upstream expense-service {
        server expense-service:8083;
    }

    server {
        listen 80;

        location /users/ {
            proxy_pass http://user-service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /groups/ {
            proxy_pass http://group-service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /expenses/ {
            proxy_pass http://expense-service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
